name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Set the base path for GitHub Pages (repository name)
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          if [ "$REPO_NAME" = "$GITHUB_REPOSITORY_OWNER.github.io" ]; then
            # For username.github.io repositories, the base is just "/"
            npm run build
          else
            # For project repositories, the base is "/repository-name/"
            npm run build -- --base=/$REPO_NAME/
          fi

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Debug build output
        run: |
          echo "Listing contents of the dist directory..."
          ls -la dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
